apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: flashcards
            namespace: apps
            gitRepo: https://gitlab.com/portfolio5815640/flashcards-gitops.git
            path: flashcards
            wave: '0'
  template:
    metadata:
      name: 'flashcards'
      annotations:
        argocd.argoproj.io/sync-wave: '0'
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: apps
      source:
        repoURL: https://gitlab.com/portfolio5815640/flashcards-gitops.git
        path: flashcards
        targetRevision: 'main'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
