apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: flashcards
            namespace: apps
            gitRepo: https://gitlab.com/portfolio5815640/flashcards-gitops.git
            path: flashcards
            wave: '0'
          # --- Logging stack components ---
          - name: elasticsearch
            namespace: logging
            gitRepo: https://gitlab.com/portfolio5815640/flashcards-gitops.git
            path: charts/logging/elasticsearch
            wave: '-2'

          - name: fluentbit
            namespace: logging
            gitRepo: https://gitlab.com/portfolio5815640/flashcards-gitops.git
            path: charts/logging/fluentbit
            wave: '-1'

          - name: kibana
            namespace: logging
            gitRepo: https://gitlab.com/portfolio5815640/flashcards-gitops.git
            path: charts/logging/kibana
            wave: '0'
  template:
    metadata:
      name: '{{name}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{wave}}'
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      source:
        repoURL: '{{gitRepo}}'
        path: '{{path}}'
        targetRevision: 'main'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true