apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: cert-manager
            namespace: cert-manager
            gitRepo: https://github.com/Lielik/flashcards-gitops.git
            path: platform/cert-manager
            wave: "0"
          - name: flashcards
            namespace: apps
            gitRepo: https://github.com/Lielik/flashcards-gitops.git
            path: flashcards
            wave: "2"
  template:
    metadata:
      name: "{{name}}"
      annotations:
        argocd.argoproj.io/sync-wave: "{{wave}}"
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      source:
        repoURL: "{{gitRepo}}"
        path: "{{path}}"
        targetRevision: "main"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
